#
# Generate config file for pov-check-health
#

pending=
prefix_called=0

prefix() {
    if [ $prefix_called -ne 0 ]; then
        pending="$pending
$@
"
    else
        pending="$@
"
        prefix_called=1
    fi
}

emit() {
    if [ -n "$pending" ]; then
        echo -n "$pending"
        pending=
    fi
    echo "$@"
}

separator() {
    prefix "
"
}

generate_checkfs() {
    prefix "# Check free disk space"
    df -PT | { read header; while read device fstype size used free capacity mountpoint; do
        case $fstype in
            tmpfs|devtmpfs|ecryptfs|nfs|vboxsf)
                ;;
            *)
                emit "checkfs $mountpoint		100M"
                ;;
        esac
    done; }
    pending=
}

generate_checkinodes() {
    prefix "# Check free inodes"
    df -PT | { read header; while read device fstype size used free capacity mountpoint; do
        case $fstype in
            tmpfs|devtmpfs|ecryptfs|nfs)
                ;;
            *)
                emit checkinodes $mountpoint
                ;;
        esac
    done; }
    pending=
}

generate_checkpidfiles() {
    prefix "# Check for stale pidfiles"
    emit "checkpidfiles /var/run/*.pid /var/run/*/*.pid"
}

generate_checkproc() {
    prefix "# Check that processes are running"
    ps --ppid 1 -o comm= | sort -u | while read cmd; do
        case $cmd in
            kthreadd/*)
                ;;
            dhclient|dhclient3)
                # these come and go, I assume
                ;;
            console-kit-dae)
                # truncated process name won't work with checkproc
                ;;
            upstart-*)
                # truncated upstart helper process names won't work with
                # checkproc; besides I'm not sure I want to explicitly
                # check for implementation details of /sbin/init...
                ;;
            master)
                emit "checkproc master # postfix"
                ;;
            collectdmon)
                emit checkproc $cmd
                emit checkproc collectd
                ;;
            screen|tmux)
                # probably transient
                ;;
            /usr/sbin/postg)
                # this is horrible, but neither checkproc nor checkproc_pgrep
                # postgrey work
                emit checkproc_pgrep_full '^/usr/sbin/postgrey'
                ;;
            *)
                emit checkproc $cmd
                ;;
        esac
    done
    pending=
}

generate_checkram() {
    prefix "# Check free memory"
    emit checkram
}

generate_checkswap() {
    prefix "# Check excessive swap usage"
    emit checkswap
}

generate_checkmailq() {
    prefix "# Check size of mail queue"
    emit checkmailq
}

generate_checkaliases() {
    prefix "# Check if /etc/aliases is up to date"
    emit checkaliases
}


generate() {
    prefix "#
# System health checks for $(hostname -f)
#
# Generated by pov-check-health on $(date +"%Y-%m-%d %H:%M:%S")
#"
    generate_checkproc
    generate_checkpidfiles
    generate_checkfs
    generate_checkinodes
    generate_checkram
    generate_checkswap
    generate_checkmailq
    generate_checkaliases
}
